### ISSUE TITLE
Usage of Lexicon

### ISSUE THREAD

**Issue by dissendahl** [solivr/tf-crnn#33]
First of all thank you for the code.
Does your implementation contain a lexicon functionality as described in the original paper?

**Comment by solivr** [comment]
Hi,
No it doesn't, the current implementation is lexicon-free.
Could be an improvement though, but it's not in the priority line for the moment...

**Comment by dissendahl** [comment]
@solivr : Thanks for the fast reply! 
I will try to incorporate a lexicon feature once i get the core training running. 

Another issue: 
I wanna learn recognition of different special characters within latin languages char space. I tried to simply add those chars to the LETTERS_%-Strings in config.py, yet train.py throws unknown alphabet error when executed. Whats the right way to add other chars?

**Comment by solivr** [comment]
Which character did you add ? If your special characters have a multibyte encoding in `utf-8` format, you will have an error (see https://github.com/solivr/tf-crnn/issues/8#issuecomment-343419029 and [here](https://github.com/tensorflow/tensorflow/issues/11399)).
Otherwise the easiest way to use your special characters is to add them to the `Alphabet` [class](https://github.com/solivr/tf-crnn/blob/master/src/config.py#L18) like this : 
``` python 
class Alphabet:
    ...
    Symbols = " '.,:;-_=(){your_special_chars}"  # {your_special_chars} are the characters you want to add
```
and then use `alphabet=Alphabet.LETTERS_EXTENDED` ([line](https://github.com/solivr/tf-crnn/blob/master/train.py#L47)) in `train.py`.
